---
# Ensure Kubernetes config directory exists
- name: Ensure /etc/kubernetes directory exists
  file:
    path: /etc/kubernetes
    state: directory
    mode: '0755'

# Create kubeadm config file (empty initially)
- name: Create an empty file for Kubeadm configuring
  copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: no

# Populate the kubeadm config
- name: Configure kubeadm config
  blockinfile:
    path: /etc/kubernetes/kubeadm-config.yaml
    block: |
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta3
      networking:
        podSubnet: "10.244.0.0/16"
      ---
      kind: KubeletConfiguration
      apiVersion: kubelet.config.k8s.io/v1beta1
      runtimeRequestTimeout: "15m"
      cgroupDriver: "systemd"
      systemReserved:
        cpu: 100m
        memory: 350M
      kubeReserved:
        cpu: 100m
        memory: 50M
      enforceNodeAllocatable:
      - pods

# Initialize Kubernetes master node
- name: Initialize the Kubernetes cluster
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml | tee /home/ubuntu/cluster_initialized.log
  register: init_result
  failed_when: "'error' in init_result.stderr or init_result.rc != 0"

# Wait for kube-apiserver to be ready before workers join
- name: Wait for API server (port 6443) to be up on master
  wait_for:
    host: "127.0.0.1"
    port: 6443
    timeout: 30


# Create .kube directory for the user
- name: Create .kube directory for ubuntu user
  become: true
  become_user: ubuntu
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: '0755'

# Copy kubeconfig to user's .kube directory
- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0644'

# Install Flannel CNI plugin
- name: Apply Flannel network plugin
  become: true
  become_user: ubuntu
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml | tee /home/ubuntu/pod_network_setup.log
  args:
    chdir: /home/ubuntu
    creates: /home/ubuntu/pod_network_setup.log
