- name: Wait for Kubernetes API server on master
  wait_for:
    host: "{{ hostvars['master'].ansible_default_ipv4.address }}"
    port: 6443
    timeout: 30

- name: Join worker to cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.log"
  args:
    chdir: /home/ubuntu
    creates: node_joined.log

