---
# on the master, generate a join command
- name: Retrieve Join Command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  run_once: true
  delegate_to: "{{ groups['master_node'][0] }}"

- name: Set Join Command fact
  set_fact:
    kube_join_cmd: "{{ join_command_raw.stdout_lines[0] }}"

# on each worker, wait for API and run the join
- name: Wait for API on master
  wait_for:
    host: "{{ hostvars[ groups['master_node'][0] ].ansible_default_ipv4.address }}"
    port: 6443
    timeout: 300

- name: Join worker to cluster
  shell: "{{ kube_join_cmd }} >> /home/ubuntu/node_joined.log"
  args:
    chdir: /home/ubuntu
    creates: /home/ubuntu/node_joined.log
