---
# Always run the baseline deps on every node in [private]
- include_tasks: dependencies.yml

- include_tasks: master_setup.yml
  when: "'master_node' in group_names"

- include_tasks: join_workers.yml
  when: "'slave_node' in group_names"
