apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
spec:
  containers:
  - name: db
    image: postgres:14.1-alpine
    ports:
    - containerPort: 5432
    envFrom:
    - configMapRef:
        name: db-configmap
