apiVersion: v1
kind: Pod
metadata:
  name: react-front
  labels:
    name: react-front
spec:
  containers:
  - name: front
    image: elasraouib/front_demo:v26
    ports:
    - containerPort: 3000
    imagePullPolicy: Always
