apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    name: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: db
        image: postgres:14.1-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-configmap
