apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front
  labels:
    name: react-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-front
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
      - name: front
        image: elasraouib/front_demo:v26
        ports:
        - containerPort: 3000
